variables:
  projectname: "Deploy CloverDX Server - Windows"
  fileincludeglob: "**/**"

stages:
  - main

image: 
  name: registry.gitlab.com/filevine/technology/project/filevine-platform/docker-gitlab-runner-linux/master:latest

default:
  tags:
    - internal
    - linux

deploy-branch:
  stage: main
  script:
    - |
      pwsh -c '
        Import-Module ./etc/New-CloverAssetsPackage.ps1
        $manifest = Import-PowershellDataFile -Path clover-assets-manifest.psd1
        New-CloverAssetsPackage -DependancyManifest $manifest
        $gitversion = gitversion | convertfrom-json
        $nupkgversion = ${gitversion}.MajorMinorPatch + "-" + ${gitversion}.PreReleaseLabel
        $releaseversion = ${gitversion}.SemVer + "+" + ${gitversion}.ShortSha + "." + $env:CI_PIPELINE_IID
        Remove-Item -Recurse -Force .git/
        octo pack --id="cloverdx-windows" --version="${nupkgversion}" --include="terraform/"
        octo pack --id="clover-assets" --version="${nupkgversion}" --include="clover-assets/"
        octo push --package="cloverdx-windows.${nupkgversion}.nupkg" --space="MigrateTech-CloverDX" --overwrite-mode="OverwriteExisting"
        octo push --package="clover-assets.${nupkgversion}.nupkg" --space="MigrateTech-CloverDX" --overwrite-mode="OverwriteExisting"

        octo create-release --project="Deploy CloverDX Assets - Windows" `
                            --space="MigrateTech-CloverDX" `
                            --package clover-assets:${nupkgversion} `
                            --packageVersion="${nupkgversion}" `
                            --version="${releaseversion}" `
                            --ignoreExisting

        octo create-release --project="Deploy CloverDX Server - Windows" `
                            --space="MigrateTech-CloverDX" `
                            --package clover-powershell:0.1.0-gitlab-ci `
                            --package="Plan:${nupkgversion}" `
                            --package="Apply:${nupkgversion}" `
                            --package="Deploy a Release:${releaseversion}" `
                            --package=" Wait for worker SQL Server to come online:${nupkgversion}" `
                            --version="${releaseversion}" `
                            --ignoreExisting'
  except:
    - master
    - tags

deploy-master:
  stage: main
  script:
    - |
      pwsh -c '
        Import-Module ./etc/New-CloverAssetsPackage.ps1
        $manifest = Import-PowershellDataFile -Path clover-assets-manifest.psd1
        New-CloverAssetsPackage -DependancyManifest $manifest
        gitversion
        $gitversion = (gitversion | convertfrom-json).SemVer
        Remove-Item -Recurse -Force .git/
        octo pack --id="cloverdx-windows" --version="${gitversion}" --include="terraform/"
        octo pack --id="clover-assets" --version="${gitversion}" --include="clover-assets/"
        octo push --package="cloverdx-windows.${gitversion}.nupkg" --space="MigrateTech-CloverDX" --overwrite-mode="OverwriteExisting"
        octo push --package="clover-assets.${gitversion}.nupkg" --space="MigrateTech-CloverDX" --overwrite-mode="OverwriteExisting"
        octo create-release --project="Deploy CloverDX Assets - Windows" --space="MigrateTech-CloverDX" --package clover-assets:${gitversion} --packageVersion="${gitversion}" --version="${gitversion}" --ignoreExisting
        octo create-release --project="Deploy CloverDX Server - Windows" --space="MigrateTech-CloverDX" --packageVersion="${gitversion}" --package="Deploy a Release:${gitversion}" --version="${gitversion}" --ignoreExisting'
  only:
    - master