envName             = "austin-test"
region              = "us-west-2"
dns_domain          = "filevinedev.com"
subdomain           = "austin-test"
shorturl_dns_domain = "filev.io"
clover_domain       = "austin-test.cloverdx.filevinedev.com"
assume_role_arn     = "arn:aws:iam::499849779868:role/Terraform"

octopus_tenant                  = "austin-test"
octopus_space                   = "MigrateTech-CloverDX"
octopus_api_key                 = "API-IGMUQIUJKLAUOFRHG55XONYMZYA"
octopus_server_environment      = "Dev"
octopus_server_address          = "http://internal-octopus.filevinedev.com:88"
octopus_provider_server_address = "http://internal-octopus.filevinedev.com:88"
instance_type                   = "c5.xlarge"
ami_status                      = "released"
aws_role                        = "arn:aws:iam::499849779868:role/Terraform"

rds_storage        = "50"
rds_max_storage    = "256"
rds_storage_type   = "gp2"
rds_engine         = "postgres"
rds_engine_version = "11.7"
rds_instance_class = "db.t3.medium"
rds_user_name      = "postgres"
rds_user_password  = "rX2s7oHIuK2O"
